// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiFinalFernandezRiesenNicolas.Models;

namespace WebApiFinalFernandezRiesenNicolas.Migrations
{
    [DbContext(typeof(DbHospitalAPIContext))]
    partial class DbHospitalAPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApiFinalFernandezRiesenNicolas.Models.Doctor", b =>
                {
                    b.Property<int>("DoctorNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Especialidad")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("HospitalCod")
                        .HasColumnType("int");

                    b.HasKey("DoctorNo");

                    b.HasIndex("HospitalCod");

                    b.ToTable("Doctor");
                });

            modelBuilder.Entity("WebApiFinalFernandezRiesenNicolas.Models.Hospital", b =>
                {
                    b.Property<int>("HospitalCod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("NumCama")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("HospitalCod");

                    b.ToTable("Hospital");
                });

            modelBuilder.Entity("WebApiFinalFernandezRiesenNicolas.Models.Doctor", b =>
                {
                    b.HasOne("WebApiFinalFernandezRiesenNicolas.Models.Hospital", "Hospital")
                        .WithMany("Doctores")
                        .HasForeignKey("HospitalCod")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
